# Generated by Django 4.1.7 on 2026-02-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0002_leaderboard_activity_count_team_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='distance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
